import http from 'node:http';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createEvent,priceUsage,createTracker,summarize,frontier} from '../src/index.js';
import {EventStore} from '../src/store.js';
import {createServer} from '../src/server.js';
function fetch(url, options={}) {
  return new Promise((resolve,reject)=>{
    const request=http.request(url,{method:options.method??'GET',headers:options.headers},response=>{
      let body='';response.on('data',chunk=>body+=chunk);response.on('end',()=>resolve({status:response.statusCode,json:async()=>JSON.parse(body)}));
    });
    request.on('error',reject);request.end(options.body);
  });
}
const rates={version:'fixture',input:1000000,cachedInput:200000,output:3000000};
const event = overrides => createEvent({project:'p',task:'t',provider:'mock',model:'m',usage:{inputTokens:1000,cachedInputTokens:200,outputTokens:100},rates,...overrides});
test('cached input is not double billed and rates use exact arithmetic',()=>{assert.equal(event().cost.nanoUsd,'1140000');assert.equal(priceUsage({inputTokens:1,outputTokens:0},rates).nanoUsd,'1000');assert.throws(()=>priceUsage({inputTokens:1,cachedInputTokens:2,outputTokens:0},rates));assert.equal(event({rates:null}).cost.status,'unknown');});
test('retries contribute spend but count as one logical unit',()=>{const rows=summarize([event({executionId:'e',status:'failed',accepted:null}),event({executionId:'e',accepted:true})]);assert.equal(rows[0].attempts,2);assert.equal(rows[0].executions,1);assert.equal(rows[0].costPerSuccess,.00228);});
test('unknown costs, missing outcomes and zero successes prevent misleading CPS',()=>{for(const e of [event({rates:null,accepted:true}),event({accepted:null}),event({accepted:false})])assert.equal(summarize([e])[0].costPerSuccess,null);});
test('frontier excludes dominated configurations within a task only',()=>{const rows=summarize([event({model:'a',accepted:true}),event({model:'b',accepted:true,rates:{...rates,input:2000000}}),event({model:'c',task:'other',accepted:true,rates:{...rates,input:2000000}})]);assert.deepEqual(frontier(rows).map(r=>r.model),['a','c']);});
test('provider failure retains billable usage and original error',async()=>{const events=[];const tracker=createTracker({record:e=>events.push(e)});const error=new Error('provider');error.usage={inputTokens:1000,outputTokens:0};await assert.rejects(tracker.track({project:'p',task:'t',provider:'p',model:'m',rates},async()=>{throw error;}),e=>e===error);assert.equal(events[0].status,'failed');assert.equal(events[0].cost.usd,.001);});
test('persistence failure preserves successful output without recording a failed inference',async()=>{let calls=0;const tracker=createTracker({record:()=>{calls++;throw new Error('disk');}});await assert.rejects(tracker.track({project:'p',task:'t',provider:'p',model:'m'},async()=>({output:'saved result'})),e=>e.output==='saved result'&&e.event.status==='completed');assert.equal(calls,1);});
test('store deduplicates concurrent writes, rejects conflicts and persists outcomes',async()=>{const dir=await mkdtemp(join(tmpdir(),'ieop-'));try{const store=new EventStore(join(dir,'events'));const e=event();await Promise.all([store.append(e),store.append(e)]);assert.equal((await store.list()).length,1);await assert.rejects(store.append({...e,model:'changed'}));await store.recordOutcome(e.executionId,true);assert.equal((await new EventStore(join(dir,'events')).list())[0].accepted,true);await assert.rejects(store.append(event({executionId:e.executionId,model:'other'})));}finally{await rm(dir,{recursive:true,force:true});}});
test('server requires authentication, validates events and rejects demo writes',async()=>{const dir=await mkdtemp(join(tmpdir(),'ieop-'));const server=createServer({store:new EventStore(join(dir,'events')),token:'test-token'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await fetch(base+'/api/report')).status,401);const headers={Authorization:'Bearer test-token','Content-Type':'application/json'};assert.equal((await fetch(base+'/api/events',{method:'POST',headers,body:JSON.stringify(event())})).status,201);assert.equal((await fetch(base+'/api/events',{method:'POST',headers,body:'{}'})).status,400);assert.equal((await (await fetch(base+'/api/report',{headers})).json()).events.length,1);assert.equal((await fetch(base+'/../../package.json')).status,404);}finally{await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}});
test('demo report is populated and demo ingestion is forbidden',async()=>{const server=createServer({demo:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const report=await (await fetch(base+'/api/report')).json();assert.equal(report.demo,true);assert.equal(report.events.length,90);assert.equal((await fetch(base+'/api/events',{method:'POST',body:'{}'})).status,403);assert.equal((await fetch(base+'/')).status,200);}finally{await new Promise(resolve=>server.close(resolve));}});
test('timestamps must be canonical UTC strings',()=>{for(const timestamp of [0,null,'September 1, 2026','2026-02-30T00:00:00.000Z'])assert.throws(()=>summarize([{...event(),timestamp}]));});
test('null provider rejection still records the failed attempt',async()=>{const events=[];const tracker=createTracker({record:e=>events.push(e)});let rejection='unset';try{await tracker.track({project:'p',task:'t',provider:'p',model:'m'},async()=>{throw null;});}catch(e){rejection=e;}assert.equal(rejection,null);assert.equal(events[0].status,'failed');});
test('HTTP ingestion preserves split multibyte UTF-8 and rejects invalid URL targets',async()=>{const dir=await mkdtemp(join(tmpdir(),'ieop-'));const server=createServer({store:new EventStore(join(dir,'events')),token:'test-token'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;try{const e=event({project:'工程 🧠'}),body=Buffer.from(JSON.stringify(e)),split=body.indexOf(Buffer.from('🧠'))+2;const status=await new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,path:'/api/events',method:'POST',headers:{Authorization:'Bearer test-token'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.write(body.subarray(0,split));setTimeout(()=>req.end(body.subarray(split)),5);});assert.equal(status,201);const report=await(await fetch(`http://127.0.0.1:${port}/api/report`,{headers:{Authorization:'Bearer test-token'}})).json();assert.equal(report.events[0].project,'工程 🧠');const bad=await new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,path:'http://['},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end();});assert.equal(bad,400);}finally{await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}});
