import {simulateCascade,selectConfiguration,forecastBudget} from '/simulation.js';
const $ = id => document.getElementById(id);
const money = n => n === null ? '—' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?4:2}).format(n);
const pct = n => n === null ? '—' : `${(n*100).toFixed(1)}%`;
let token = '', report;
const element = (tag,text,className) => {const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;};
function tableRow(values){const tr=element('tr','');for(const v of values)tr.append(element('td',v));return tr;}
async function load(){
  $('error').textContent='';
  try {
    const response=await fetch(`/api/report?project=${encodeURIComponent($('project').value)}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});
    if(response.status===401){$('auth').hidden=false;$('mode').textContent='Authentication required';return;}
    if(!response.ok)throw new Error('Could not load report');
    report=await response.json();updateAdvanced();$('auth').hidden=true;$('mode').textContent=report.demo?'DEMO • illustrative data':'LOCAL • recorded data';
    const selected=$('project').value;$('project').replaceChildren(new Option('All projects',''),...report.projects.map(p=>new Option(p,p)));$('project').value=selected;
    const rows=report.rows, spend=rows.reduce((a,r)=>a+r.knownSpend,0), unpriced=rows.reduce((a,r)=>a+r.unpriced,0), units=rows.reduce((a,r)=>a+r.executions,0), successes=rows.reduce((a,r)=>a+r.successes,0), observed=rows.reduce((a,r)=>a+r.observed,0);
    $('spend').textContent=money(spend);$('coverage').textContent=`${unpriced} unpriced attempts`;$('cps').textContent=money(!unpriced&&observed===units&&successes?spend/successes:null);$('success').textContent=pct(observed?successes/observed:null);$('outcomes').textContent=`${observed}/${units} outcomes observed`;$('attempts').textContent=report.events.length;$('units').textContent=`${units} logical executions`;
    $('models').replaceChildren(...rows.map(r=>tableRow([`${r.model} / ${r.task}`,money(r.knownSpend),`${r.successes}/${r.observed} (${pct(r.successRate)})`,money(r.costPerSuccess),`${(r.p95LatencyMs/1000).toFixed(2)}s`,`${pct(r.outcomeCoverage)} outcomes; ${r.unpriced} unpriced`])));
    $('events').replaceChildren(...report.events.slice().sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,50).map(e=>tableRow([e.model,e.task,e.status,e.accepted===null?'Unknown':e.accepted?'Accepted':'Rejected',money(e.cost.usd),e.usage?`${e.usage.inputTokens} in / ${e.usage.outputTokens} out`:'Unavailable'])));
    const byModel=new Map();for(const r of rows)byModel.set(r.model,(byModel.get(r.model)||0)+r.knownSpend);
    $('bars').replaceChildren();const maximum=Math.max(...byModel.values(),1e-9);
    for(const [model,cost] of byModel){const row=element('div','','bar-row'),label=element('div','','bar-label');label.append(element('span',model),element('span',money(cost)));const track=element('div','','bar-track'),bar=element('div','','bar');bar.style.width=`${cost/maximum*100}%`;track.append(bar);row.append(label,track);$('bars').append(row);}
    $('frontier').replaceChildren(...report.frontier.map(r=>{const e=element('div',`${r.model} · ${r.task}`,'frontier-item');e.append(element('small',`${money(r.knownSpend/r.executions)} / task · ${pct(r.successRate)} accepted · n=${r.executions}`));return e;}));
    if(!rows.length){$('bars').textContent='No events yet. Run npm run example to record your first attempts.';$('frontier').textContent='No evaluated configurations yet.';}
  }catch(error){$('error').textContent=error.message;}
}
$('project').addEventListener('change',load);$('refresh').addEventListener('click',load);$('connect').addEventListener('click',()=>{token=$('token').value;$('token').value='';load();});
$('export').addEventListener('click',()=>{if(!report)return;const keys=['project','task','provider','model','attempts','executions','knownSpend','unpriced','successes','observed','costPerSuccess'];const csv=[keys,...report.rows.map(r=>keys.map(k=>r[k]??''))].map(row=>row.map(v=>{const s=String(v);return '"'+(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=element('a','');a.href=url;a.download='inference-economics.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
load();
const ns='http://www.w3.org/2000/svg';
function svgNode(tag,attrs={},text){const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;}
function chartFrame(id,label){const svg=svgNode('svg',{viewBox:'0 0 800 260',role:'img','aria-label':label});$(id).replaceChildren(svg);return svg;}
function drawTrend(){const svg=chartFrame('trend','Daily known inference spend');const days=new Map();for(const e of report.events){const d=e.timestamp.slice(0,10);days.set(d,(days.get(d)||0)+(e.cost.usd??0));}const values=[...days].sort(([a],[b])=>a.localeCompare(b));if(!values.length){svg.append(svgNode('text',{x:30,y:120},'Record events to see your spend trend'));return;}const max=Math.max(...values.map(v=>v[1]),1e-9);for(let i=0;i<4;i++){const y=30+i*55;svg.append(svgNode('line',{x1:70,x2:770,y1:y,y2:y}),svgNode('text',{x:2,y:y+4},money(max*(1-i/3))));}const coords=values.map((v,i)=>[70+i/Math.max(values.length-1,1)*700,195-v[1]/max*165]);const path=coords.map((p,i)=>`${i?'L':'M'}${p.join(',')}`).join(' ');svg.append(svgNode('path',{d:path+' L770,195 L70,195 Z',fill:'#88b55d',opacity:'.12'}),svgNode('path',{d:path,fill:'none',stroke:'#83ab57','stroke-width':3}));for(let i=0;i<values.length;i+=Math.max(1,Math.floor(values.length/6))){svg.append(svgNode('text',{x:coords[i][0],y:228,'text-anchor':'middle'},values[i][0].slice(5)));}for(const [i,p]of coords.entries()){const dot=svgNode('circle',{cx:p[0],cy:p[1],r:4,fill:'#789f4f'});dot.append(svgNode('title',{},`${values[i][0]}: ${money(values[i][1])}`));svg.append(dot);}}
function cohortRows(){return report?.rows.filter(r=>JSON.stringify([r.project,r.task])===$('cohort').value)??[];}
function drawLab(){if(!report)return;const rows=cohortRows(),quality=Number($('quality').value)/100;$('quality-label').textContent=pct(quality);const svg=chartFrame('scatter','Inference cost versus acceptance for selected task cohort');const eligible=rows.filter(r=>!r.unpriced&&r.outcomeCoverage===1&&r.successRate!==null);const max=Math.max(...eligible.map(r=>r.knownSpend/r.executions),.000001);for(let i=0;i<=4;i++){const y=25+i*45;svg.append(svgNode('line',{x1:65,x2:770,y1:y,y2:y}),svgNode('text',{x:10,y:y+4},`${100-i*25}%`));}svg.append(svgNode('line',{x1:65,x2:770,y1:205-quality*180,y2:205-quality*180,stroke:'#98b773','stroke-dasharray':'5 5'}));for(const r of eligible){const x=85+(r.knownSpend/r.executions)/max*600,y=205-r.successRate*180;const dot=svgNode('circle',{cx:x,cy:y,r:8,fill:r.successRate>=quality?'#87ad56':'#b49a86'});dot.append(svgNode('title',{},`${r.model}: ${money(r.knownSpend/r.executions)} / task, ${pct(r.successRate)}, n=${r.executions}`));svg.append(dot,svgNode('text',{x,y:y-16,'text-anchor':'middle'},r.model),svgNode('text',{x,y:230,'text-anchor':'middle'},money(r.knownSpend/r.executions)));}if(!eligible.length)svg.append(svgNode('text',{x:90,y:115},'No fully priced and evaluated configurations in this cohort'));const best=selectConfiguration(rows,{qualityTarget:quality,maxLatencyMs:Number($('latency').value)*1000,maxCost:Number($('max-cost').value)});$('route-result').textContent=best?`Candidate: ${best.model} · ${money(best.knownSpend/best.executions)} / task · ${pct(best.successRate)} acceptance · ${(best.p95LatencyMs/1000).toFixed(2)}s p95. Descriptive sample, n=${best.executions}.`:'No eligible configuration meets these constraints. Missing outcomes or prices exclude a configuration.';$('lab-result').textContent=`${eligible.length} eligible configurations · ${rows.length-eligible.length} excluded for missing prices or outcomes · ${eligible.filter(r=>r.successRate>=quality).length} meet the acceptance target.`;}
function planning(){try{const result=simulateCascade({requests:Number($('requests').value),cheapCost:Number($('cheap-cost').value),strongCost:Number($('strong-cost').value),gateCost:Number($('gate-cost').value),escalationRate:Number($('escalation').value)/100});$('escalation-label').textContent=$('escalation').value+'%';$('cascade-result').textContent=`Baseline ${money(result.baseline)} → modeled ${money(result.proposed)} · ${money(result.savings)} savings (${pct(result.savingsRate)}) · ${result.escalations.toLocaleString()} expected escalations.`;}catch(e){$('cascade-result').textContent=e.message;}try{const result=forecastBudget({spend:Number($('budget-spend').value),elapsedDays:Number($('elapsed').value),totalDays:Number($('days').value),budget:Number($('budget').value)});$('budget-result').textContent=`Forecast ${money(result.forecast)} · remaining ${money(result.remaining)} · projected overrun ${money(result.overrun)} · budget used ${pct(result.utilization)}.`;}catch(e){$('budget-result').textContent=e.message;}}
function updateAdvanced(){const selected=$('cohort').value;const cohorts=[...new Map(report.rows.map(r=>[JSON.stringify([r.project,r.task]),`${r.project} / ${r.task}`])).entries()];$('cohort').replaceChildren(...cohorts.map(([key,label])=>new Option(label,key)));if(cohorts.some(([key])=>key===selected))$('cohort').value=selected;$('signal').textContent=`${report.events.length} attempts · ${report.demo?'synthetic dataset':'local telemetry'}`;drawTrend();drawLab();planning();}
for(const id of ['cohort','quality','latency','max-cost'])$(id).addEventListener('input',()=>{try{drawLab();}catch(e){$('route-result').textContent=e.message;}});
for(const id of ['requests','cheap-cost','strong-cost','gate-cost','escalation','budget-spend','elapsed','days','budget'])$(id).addEventListener('input',planning);
$('theme').addEventListener('click',()=>document.body.classList.toggle('dark'));
$('events').addEventListener('click',e=>{const row=e.target.closest('tr');if(!row||!report)return;const sorted=report.events.slice().sort((a,b)=>b.timestamp.localeCompare(a.timestamp));const event=sorted[[...$('events').children].indexOf(row)];if(!event)return;$('request-detail').textContent=JSON.stringify(event,null,2);$('inspector').showModal();});
$('close-inspector').addEventListener('click',()=>$('inspector').close());
